######################## default configuration ####################
baseURL = "https://rinpharma.com"
languageCode = "en-us"
title = "R/Pharma"
theme = "clusterai-hugo"
summaryLength = "10"
paginate = 4

## deploy to docs for github pages
publishDir = "docs"

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/themefisher-font/style.css"

  [[params.plugins.extracss]]
  URL = "css/custom.css"
  

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jquery/jquery.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/SyoTimer/jquery.syotimer.min.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.32/jquery.form.js"
  [[params.plugins.js]]
  URL = "http://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.1/jquery.validate.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"
  [[params.plugins.js]]
  URL = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 2

  [[menu.main]]
  weight = 4
  name = "Menu"
  hasChildren = true


    [[menu.main]]
    parent = "Menu"
    weight = 1
    name = "Blog"
    URL = "blog"

#    [[menu.main]]
#    parent = "Menu"
#    name = "Schedule"
#    URL = "schedule"


    [[menu.main]]
    parent = "Menu"
    weight = 9
    name = "Contact"
    URL = "https://epijim.typeform.com/to/zy7oAM"

#################### default parameters ################################
[params]
logo = "images/logotext_small.png"
home = "Home"
# Meta data
description = "R/Pharma - 2020 Conference for practitioners of R in the Pharmaceutical Industry"
author = "R/Pharma"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-168676822-1"

  # Preloader
  [params.preloader]
  enable = true

  # Navigation get start button
  [params.navBtn]
  enable = false
  label = "Get Ticket"
  link = "LINK TO TICKETS"

  ############################## footer ################################
  [params.footer]
  title = "R/Pharma"
  content = "Using R to bring medicines to patients."
  copyright = "R/Pharma"

  ############################# social icon ############################

  [[params.social]]
  icon = "tf-ion-social-twitter"
  link = "https://twitter.com/rinpharma?lang=en"
