baseurl: "http://rinpharma.com"
title: "R/Pharma"
canonifyurls: true
theme: "hugo-conference"
publishDir: "docs"

GoogleAnalytics: "UA-109863434-1"

params:
  # Conference info
  Name: "R / Pharma"
  Description: "Using R to bring medicines to patients"
  Date: "August 21, 22, and 23, 2019"
  #Price: "Registration closes April 1st" # If your event is free, just comment this line
  Venue: "Harvard University"
  Address: "Harvard University, CGIS South, Cambridge Street, Cambridge, MA, USA"
  City:  "Cambridge"
  State: "MA"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - keynotes
    - workshops
    - call4papers
    - location
    #- hotel
    - programs
    - grants
    #- sponsors
    #- governance
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    call4papers: "Call for papers"
    hotel: "Hotel"
    location: "Location"
    keynotes: "Keynotes"
    workshops: "Workshops"
    schedule: "Schedule"
    sponsors: "Sponsors"
    grants: "Scholars"
    programs: "Programs"
    governance: "Governance"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Click here to register now!"
  #  link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Programs
  Programs:
    - name: "2018 program"
      logo: "/img/2018programshot.jpeg"
      url: "http://rinpharma.com/program/"

  # List of Sponsors
  Sponsors:
    - name: "R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # List of Partners
  Governance:
    - name: "Also the R-Consortium"
      logo: "/img/r_consortium.jpg"
      url: "https://www.r-consortium.org/"

  # The keynotes
  Keynotes:

    - name: "Garrett Grolemund"
      affaliation: "RStudio"
      photo: "/img/GarrettGrolemund.png"
      bio: "Garrett Grolemund is the co-author of R for Data Science and R Markdown: The Definitive Guide, as well as the author of Hands-On Programming with R. He wrote the lubridate R package and works for RStudio as both an educator and advocate of data science with R."
      title: "Title TBD"
      link:
        href: "https://github.com/garrettgman"
        text: "Github"

    - name: "Paul Schuette"
      affaliation: "FDA"
      photo: "/img/PaulSchuette.png"
      bio: "Scientific Computing Coordinator for the Office of Biostatistics. Paul serves as subject matter expert for Scientific and Statistical Computing, manages scientific workstations, acquisition and deployment of software, and with additional projects dealing with statistical methodology appropriate for pregnancy registries and clinical trials."
      title: "Title TBD"
      link:
        href: "https://blog.revolutionanalytics.com/2017/06/r-fda.html"
        text: "Blog on R use at the FDA"

    - name: "Leon Jessen"
      affaliation: "Technical University of Denmark"
      photo: "/img/LeonJessen.png"
      bio: "Leon is an Assistant Professor in the Immunoinformatics and Machine Learning Group (Morten Nielsen Lab) at the Section for Bioinformatics at Technical University of Denmark. I apply advanced machine learning methods to model molecular interactions in the human immune system."
      title: "Title TBD"
      link:
        href: "https://github.com/leonjessen"
        text: "Github"

  # The workshops
  Workshops:

    - name: "Joe"
      affaliation: "RStudio"
      photo: "/img/GarrettGrolemund.png"
      bio: "Garrett Grolemund is the co-author of R for Data Science and R Markdown: The Definitive Guide, as well as the author of Hands-On Programming with R. He wrote the lubridate R package and works for RStudio as both an educator and advocate of data science with R."
      title: "Title TBD"
      link:
        href: "https://github.com/garrettgman"
        text: "Github"

    - name: "Leon"
      affaliation: "FDA"
      photo: "/img/PaulSchuette.png"
      bio: "Scientific Computing Coordinator for the Office of Biostatistics. Paul serves as subject matter expert for Scientific and Statistical Computing, manages scientific workstations, acquisition and deployment of software, and with additional projects dealing with statistical methodology appropriate for pregnancy registries and clinical trials."
      title: "Title TBD"
      link:
        href: "https://blog.revolutionanalytics.com/2017/06/r-fda.html"
        text: "Blog on R use at the FDA"

    - name: "Andy"
      affaliation: "Technical University of Denmark"
      photo: "/img/LeonJessen.png"
      bio: "Leon is an Assistant Professor in the Immunoinformatics and Machine Learning Group (Morten Nielsen Lab) at the Section for Bioinformatics at Technical University of Denmark. I apply advanced machine learning methods to model molecular interactions in the human immune system."
      title: "Title TBD"
      link:
        href: "https://github.com/leonjessen"
        text: "Github"

    - name: "Max"
      affaliation: "Technical University of Denmark"
      photo: "/img/LeonJessen.png"
      bio: "Leon is an Assistant Professor in the Immunoinformatics and Machine Learning Group (Morten Nielsen Lab) at the Section for Bioinformatics at Technical University of Denmark. I apply advanced machine learning methods to model molecular interactions in the human immune system."
      title: "Title TBD"
      link:
        href: "https://github.com/leonjessen"
        text: "Github"
