name: build_and_deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master # TEMP while testing (trigger via PR)

jobs:
  blogdown:
    name: build_and_push_to_gh_pages
    runs-on: ubuntu-latest
    env:
      GOOGLESHEETS4_PASSWORD: ${{ secrets.GOOGLESHEETS4_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown and blogdown
        run: Rscript -e 'install.packages(c("rmarkdown","blogdown","googlesheets4","tidyverse","pins","glue"))'
      - name: Install tidyverse
        run: Rscript -e 'install.packages("tidyverse")'
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo(extended = TRUE, version = "0.82.0")'
      #- name: Get themes
      #  run: git submodule update --remote
      #- name: Look at files
      #  run: Rscript -e 'dir()'
      - name: Build team
        run: Rscript -e 'source("build_scripts/build_team.R")'
      - name: Run hugo_build()
        run: Rscript -e 'blogdown::hugo_build(local = FALSE)'
      #- name: Look at files post run
      #  run: Rscript -e 'list.files(recursive = TRUE)'
      #- name: Look at files in public
      #  run: Rscript -e 'dir("public")'
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
